// <auto-generated />
using System;
using GoodnwsWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoodnwsWebApp.Migrations
{
    [DbContext(typeof(GoodnwsDbContext))]
    [Migration("20181231161530_CreateTable-Stories")]
    partial class CreateTableStories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoodnwsWebApp.Models.Story", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Confidence");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<string>("Source");

                    b.Property<string>("Summary");

                    b.Property<string>("Title");

                    b.Property<int>("Votes");

                    b.HasKey("Link");

                    b.ToTable("Stories");
                });
#pragma warning restore 612, 618
        }
    }
}
