// <auto-generated />
using System;
using GoodnwsWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoodnwsWebApp.Migrations
{
    [DbContext(typeof(GoodnwsDbContext))]
    [Migration("20190104111027_Renamed-votes-column-to-flagged")]
    partial class Renamedvotescolumntoflagged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GoodnwsWebApp.Models.Story", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Confidence");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("Flagged");

                    b.Property<string>("Image");

                    b.Property<string>("Source");

                    b.Property<string>("Summary");

                    b.Property<string>("Title");

                    b.HasKey("Link");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Link = "http://feeds.reuters.com/~r/Reuters/UKTopNews/~3/ibz6VwkwsDI/please-no-brexit-talk-merkel-macron-hit-the-bar-for-beer-and-fries-idUKKCN1MS1CX",
                            Confidence = 0.75f,
                            Date = new DateTime(2018, 10, 18, 9, 52, 0, 0, DateTimeKind.Unspecified),
                            Description = "Angela Merkel, Emmanuel Macron and the leaders of Belgium and Luxembourg surprised late-night drinkers by dropping by a Brussels bar for beer and fries after an evening of summitry on Brexit with British Prime Minister Theresa May.",
                            Flagged = 0,
                            Source = "Reuters: Top News",
                            Summary = "Angela Merkel, Emmanuel Macron and the leaders of Belgium and Luxembourg surprised late-night drinkers by dropping by a Brussels bar for beer and fries after an evening of summitry on Brexit with British Prime Minister Theresa May.",
                            Title = "Please, no Brexit talk: Merkel, Macron hit the bar for beer and fries"
                        },
                        new
                        {
                            Link = "http://www.independent.co.uk/news/uk/home-news/bristol-university-cleaner-students-jamaica-holiday-herman-gordon-a8544936.html",
                            Confidence = 0.99f,
                            Date = new DateTime(2018, 9, 19, 16, 54, 0, 0, DateTimeKind.Unspecified),
                            Description = "Long-serving staff member shares pictures from the trip with his wife Denise",
                            Flagged = 0,
                            Image = "https://static.independent.co.uk/s3fs-public/styles/feed/public/thumbnails/image/2018/09/19/13/gordon.jpg",
                            Source = "The Independent - UK",
                            Summary = "Long-serving staff member shares pictures from the trip with his wife Denise",
                            Title = "Bristol University cleaner enjoys holiday to Jamaica paid for by students"
                        },
                        new
                        {
                            Link = "http://www.independent.co.uk/news/uk/home-news/dolphins-filmed-jumping-for-joy-cornwall-cornish-coast-heatwave-weather-lands-end-a8416351.html",
                            Confidence = 0.82f,
                            Date = new DateTime(2018, 6, 25, 17, 28, 0, 0, DateTimeKind.Unspecified),
                            Description = "The pod of bottlenoses followed tourist boat for more than a mile",
                            Flagged = 0,
                            Image = "https://static.independent.co.uk/s3fs-public/styles/feed/public/thumbnails/image/2018/06/25/16/splashing-time-173308.jpg",
                            Source = "The Independent - UK",
                            Summary = "The pod of bottlenoses followed tourist boat for more than a mile",
                            Title = "Dolphins filmed jumping for joy off Cornish coast as Britain basks in heatwave"
                        },
                        new
                        {
                            Link = "http://feeds.reuters.com/~r/Reuters/UKTopNews/~3/22D9saZ5EOM/sealed-with-a-kiss-newlyweds-harry-and-meghan-delight-windsor-crowds-idUKKCN1IJ2VX",
                            Confidence = 0.77f,
                            Date = new DateTime(2018, 5, 19, 15, 32, 0, 0, DateTimeKind.Unspecified),
                            Description = "WINDSOR, England (Reuters) - Prince Harry and his bride Meghan married on Saturday in a dazzling ceremony that blended ancient English ritual with African American culture, watched up close by royals and celebrities and from afar by a global TV audience...",
                            Flagged = 0,
                            Image = "s3.reutersmedia.net/resources/r/?m=02&d=20180519&t=2&i=1263743607&r=LYNXNPEE4I0E6&w=1200",
                            Source = "Reuters: Top News",
                            Summary = "WINDSOR, England (Reuters) - Prince Harry and his bride Meghan married on Saturday in a dazzling ceremony that blended ancient English ritual with African American culture, watched up close by royals and celebrities and from afar by a global TV audience of millions.",
                            Title = "Sealed with a kiss - newlyweds Harry and Meghan delight Windsor crowds"
                        },
                        new
                        {
                            Link = "http://www.bbc.co.uk/news/uk-northern-ireland-43802862",
                            Confidence = 0.9f,
                            Date = new DateTime(2018, 4, 17, 17, 47, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cows in Glarryford, County Antrim, taste freedom as they are released into a field after winter indoors.",
                            Flagged = 0,
                            Image = "http://c.files.bbci.co.uk/16B8F/production/_100917039_p064ldwk.jpg",
                            Source = "BBC News - UK",
                            Summary = "Cows in Glarryford, County Antrim, taste freedom as they are released into a field after winter indoors.",
                            Title = "County Antrim cows jump for joy after winter indoors"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
